version: "3"
services:      
    app:
        build:
            context: .
            dockerfile: Application/Dockerfile
        ports:
            - "8080:8080"
    
    mysql:
        image: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=golang
        expose: 
            - 3306
        
        volumes:
            - ./mysql/DB:/docker-entrypoint-initdb.d
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./mysql/details:/var/lib/mysql