version: "3"
services:      
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
    
    mysql:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABSE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        expose: 
            - 3306    
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d

    # phpmyadmin:
    #     container_name: test_phpmyadmin
    #     image: phpmyadmin/phpmyadmin
    #     environment:
    #         - PMA_ARBITRARY=1
    #         - PMA_HOSTS=mysql
    #         - PMA_USER=user
    #         - PMA_PASSWORD=password
    #     ports:
    #         - 8081:80